---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
#import data and explore them
```{r}
df = read.table("dnd_monsters.txt",header = TRUE)
summary(df)
```


```{r}
data <-df[,-9]
```

# do the data need to be tweaked?
## variance
if the varinaces differ too much we could scale the data
```{r}
x = sapply(data,var)
print(max(x))
print(min(x))
```
## means
if the means differ too we could center the data
```{r}
x = sapply(data,mean)
print(max(x))
print(min(x))
```
## if the distributions are not normal we can log the data
```{r}
x = sapply(data,shapiro.test)
x
```

# perform PCA
```{r}
pca <- prcomp(data, center = TRUE, scale = TRUE)
summary(pca)
```
## show variance
```{r}
pca$sd #variance explined
pca$center #means subtracted during centering
pca$scale #scaling applied during scaling
```

```{r}
pca.explainedVar = cumsum(pca$sd^2 / sum(pca$sd^2 ))
plot(pca.explainedVar,
      type = "b", # type of line
      xlab = "Number of components", 
      ylab = "Cumulative variance explained (%)",
      main = "Cumulative variance explained")
abline(h = 0.9, col = "red")
```
# loadings
```{r}
#Loadings:
# coefficients of the linear combination of the original variables that defines each principal component
pca$rotation
```
```{r}
pca.loadings = pca$rotation
for (i in 1:3){
  pca.loadings[,i]
  barplot(pca.loadings[,i], main = paste("PC", i), cex.names = 0.4)
}
```

# scores
```{r}
pca$x
# predict(pca) is also a possible command
```
#plot
```{r}
 fviz_pca_biplot( pca,
                  label = "var",
                  habillage = df$size,
                  addEllipses=FALSE, ellipse.level=0.85,
                  select.ind = list(name = c("aarakocra")))
point = predict(pca,data[1,])
point = subset(point,select = c(1,2))
point
```
```{r}
fviz_pca_var(pca)
```


# project a point in the space
```{r}
# transofrm data to the new space
point = predict(pca,data[1,])
point = subset(point,select = c(1,2))
point
```
```{r}
biplot(pca
       )
abline(v = point[1], col = "red")
abline(h = point[2], col = "green")
```


```{r}
library(factoextra)
```


